language: ruby
cache: bundler
rvm:
  - 2.2.0
  - 2.1.2

env:
  - DB=mysql
  - DB=sqlite
  - DB=postgresql
#  - DB=postgresql
before_install:
  - cp config/travis_database.yml config/database.yml
  - export TZ=Europe/Paris
  - date
  - mkdir -p public/system/identicons
install:
  - if [[ $DB = sqlite ]]; then bash .travis.install-sqlite.sh; fi;

script:
  - sqlite3 --version
  - export RAILS_ENV=test
  - bundle install
  - bundle exec rake db:create db:migrate
  - bundle exec rake db:test:prepare
  - time bundle exec rake test:all COVERAGE=true

addons:
  code_climate:
    repo_token: 4c1f9795200b13185ca2c635c767423cb3af024fdf83c4404beed70b3c698e75