sqlite: &sqlite
  adapter: sqlite3
  database: ":memory:"

mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: rorganize_travis_<%= Rails.env %>

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: rorganize_travis_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "mysql" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults